export default {
  FETCH_TRADE_LIST: 'trade_board/FETCH_TRADE_LIST',
  FETCH_TRADE_LIST_FAIL: 'trade_board/FETCH_TRADE_LIST_FAIL',
  FETCH_TRADE_LIST_SUCCESS: 'trade_board/FETCH_TRADE_LIST_SUCCESS',

  ADD_NEW_TRADE: 'trade_board/ADD_NEW_TRADE',
  ADD_NEW_TRADE_FAIL: 'trade_board/ADD_NEW_TRADE_FAIL',
  ADD_NEW_TRADE_SUCCESS: 'trade_board/ADD_NEW_TRADE_SUCCESS',
}
